os: linux
dist: focals

env:
- IMAGE=minicreative/bomb-my-backyard

branches:
  only:
  - main

services:
- docker

install:
- sudo snap install kubectl --classic

script:
- docker build -t "$IMAGE:$TRAVIS_BUILD_NUMBER" .

before_deploy:
- mkdir ${HOME}/.kube
- echo "$KUBECONFIG_ENC" | base64 --decode > ${HOME}/.kube/config
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker tag "$IMAGE:$TRAVIS_BUILD_NUMBER" "$IMAGE:latest"
- docker image push --all-tags $IMAGE

deploy:
- provider: script
  skip_cleanup: true
  script: kubectl set image deployment/bomb-my-backyard "main=$IMAGE:$TRAVIS_BUILD_NUMBER"
  on:
    branch: main
